- id: awesome-lint
  name: awesome-lint
  description: "Run awesome-lint for your awesome list repo"
  entry: hooks/awesome-lint.sh
  language: script
  args: []
  files: README.md
  verbose: true
  require_serial: true
  minimum_pre_commit_version: "0"
