-   id: awesome-lint
    name: awesome-lint
    description: ''
    entry: awesome-lint
    language: node
    'types': [javascript]
    args: []
    require_serial: false
    additional_dependencies: ["awesome-lint@0.12.1"]
    minimum_pre_commit_version: '0'
