- id: awesome-lint
  name: awesome-lint
  description: 'Run awesome-lint on markdown files'
  entry: awesome-lint
  language: node
  'types': [markdown]
  args: []
  require_serial: false
  additional_dependencies: ["awesome-lint@1.1.0"]
  minimum_pre_commit_version: '0'